# Builds and deploys the page after updates
name: Deploy to Production

# Note: I've made some changes to this workflow file simply because I need to test out some stuff.

on:
  workflow_dispatch:
    # No further properties
    
env:
  WORKFLOW_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Should run if the env variable is good
      if: ${{ env.WORKFLOW_DISPATCH }}
      run: 'echo "Was workflow dispatch!"'
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # Now we can build the thing
    - name: Build the page
      run: bundle exec jekyll build
    # Deploy to the server
